DROP DATABASE IF EXISTS sonqollay;
CREATE DATABASE IF NOT EXISTS sonqollay;
USE sonqollay;
CREATE TABLE User
(
    Id mediumint auto_increment not null primary key,
    Nombre varchar(100) not null,
    Apellido varchar(100) not null,
    Email varchar(100) not null,
    Passwd varchar(100) not null
);
CREATE TABLE Liderazgo
(
    Id mediumint auto_increment not null primary key,
    Numero int not null,
    Pregunta varchar(1000) not null,
    Alt1 varchar(1000)not null,
    Alt2 varchar(1000)not null,
    Alt3 varchar(1000)not null,
    Alt4 varchar(1000)not null,
    Explicacion varchar(1000)not null
);
CREATE TABLE Empatia
(
    Id mediumint auto_increment not null primary key,
    Numero int not null,
    Pregunta varchar(1000) not null,
    Alt1c varchar(1000)not null,
    Alt2 varchar(1000)not null,
    Alt3 varchar(1000)not null,
    Alt4 varchar(1000)not null,
    Explicacion varchar(1000)not null
);
CREATE TABLE Resiliencia
(
    Id mediumint auto_increment not null primary key,
    Numero int not null,
    Pregunta varchar(1000) not null,
    Alt1c varchar(1000)not null,
    Alt2 varchar(1000)not null,
    Alt3 varchar(1000)not null,
    Alt4 varchar(1000)not null,
    Rpta char not null,
    Explicacion varchar(1000)not null
);
CREATE TABLE Comunicacion_Asertiva
(
    Id mediumint auto_increment not null primary key,
    Numero int not null,
    Pregunta varchar(1000) not null,
    Alt1c varchar(1000)not null,
    Alt2 varchar(1000)not null,
    Alt3 varchar(1000)not null,
    Alt4 varchar(1000)not null,
    Explicacion varchar(1000)not null
);
CREATE TABLE Gestion_del_tiempo
(
    Id mediumint auto_increment not null primary key,
    Numero int not null,
    Pregunta varchar(1000) not null,
    Alt1c varchar(1000)not null,
    Alt2 varchar(1000)not null,
    Alt3 varchar(1000)not null,
    Alt4 varchar(1000)not null,
    Explicacion varchar(1000)not null
);
INSERT INTO Liderazgo(Numero, Pregunta, Alt1, Alt2, Alt3, Alt4, Explicacion)
VALUES
    (1,'Imagina que te encuentras liderando un equipo en el que varios miembros están desmotivados y muestran falta de compromiso. ¿Cuál sería la estrategia más efectiva para abordar esta situación?','Promover una comunicación abierta y fomentar la participación activa de los miembros en la toma de decisiones del equipo.','Asumir que la falta de motivación es responsabilidad exclusiva de los miembros y no intervenir. ','Implementar un sistema de recompensas individuales para incentivar el rendimiento de cada miembro. ','Tomar decisiones de manera unilateral y establecer metas más ambiciosas para aumentar la motivación. ','Promover una comunicación abierta y fomentar la participación activa de los miembros es la estrategia más efectiva para abordar la falta de motivación y compromiso en el equipo. Al permitir que los miembros se expresen, se escuchen sus opiniones y se involucren en la toma de decisiones, se fomenta su sentido de pertenencia y se promueve un ambiente colaborativo. Esto ayuda a mejorar la motivación y el compromiso de los miembros con el equipo y sus tareas.'),
    (2,'Estás liderando un proyecto complejo y uno de tus miembros clave ha cometido un error que podría afectar el resultado final. ¿Qué acción sería más adecuada como líder? ','Brindar retroalimentación constructiva y trabajar en conjunto para encontrar soluciones y mitigar el impacto del error.','Culpar y castigar públicamente al miembro por el error cometido.','Ignorar el error y confiar en que no tendrá un impacto significativo en el proyecto.','Reasignar las tareas del miembro a otros para evitar futuros errores.','Brindar retroalimentación constructiva y trabajar en conjunto para encontrar soluciones y mitigar el impacto del error es la acción más adecuada como líder. Culpar y castigar públicamente al miembro solo generaría un ambiente de desconfianza y miedo al error, lo que afectaría negativamente la colaboración y la productividad del equipo. Al brindar retroalimentación constructiva y trabajar en conjunto, se promueve el aprendizaje y se busca encontrar soluciones para resolver la situación de manera efectiva.'),
    (3,'Estás liderando un equipo en el que hay una diversidad de opiniones y enfoques para abordar un problema. ¿Cuál sería una estrategia efectiva para tomar una decisión como líder?','Facilitar una discusión abierta y respetuosa, considerando todas las perspectivas antes de tomar una decisión.','Ignorar las opiniones divergentes y tomar una decisión basada únicamente en tu propio criterio.','Tomar una votación rápida y seguir la mayoría sin tener en cuenta todas las perspectivas.','Delegar la responsabilidad de la toma de decisiones a otro miembro del equipo.','Facilitar una discusión abierta y respetuosa, considerando todas las perspectivas antes de tomar una decisión, es una estrategia efectiva como líder. Ignorar las opiniones divergentes o tomar decisiones basadas únicamente en tu propio criterio puede generar descontento y limitar la creatividad y la innovación en el equipo. Al facilitar una discusión abierta y respetuosa, se promueve el intercambio de ideas, se consideran diferentes perspectivas y se toma una decisión más informada y consensuada.'),
    (4,'Estás liderando un equipo en el que algunos miembros no cumplen con sus responsabilidades asignadas. ¿Cuál sería la acción más adecuada como líder?','Tener una conversación privada con los miembros incumplidores, estableciendo expectativas claras y consecuencias por no cumplir.','Ignorar el incumplimiento y esperar a que los miembros corrijan su comportamiento por sí solos.','Reasignar las tareas de los miembros incumplidores a otros miembros más responsables.','Sancionar públicamente a los miembros incumplidores para generar un ejemplo y disciplina en el equipo.','Tener una conversación privada con los miembros incumplidores, estableciendo expectativas claras y consecuencias por no cumplir, es la acción más adecuada como líder. Ignorar el incumplimiento o reasignar tareas solo perpetúa el problema y puede generar resentimiento en otros miembros. Sancionar públicamente también puede afectar negativamente el ambiente de trabajo. Al tener una conversación privada, se establecen expectativas claras y se brinda la oportunidad de corregir el comportamiento y comprometerse con el cumplimiento de las responsabilidades asignadas.'),
    (5,'Estás liderando un equipo en el que algunos miembros no cumplen con sus responsabilidades asignadas. ¿Cuál sería la acción más adecuada como líder?','Tener una conversación privada con los miembros incumplidores, estableciendo expectativas claras y consecuencias por no cumplir.','Ignorar el incumplimiento y esperar a que los miembros corrijan su comportamiento por sí solos.','Reasignar las tareas de los miembros incumplidores a otros miembros más responsables.','Sancionar públicamente a los miembros incumplidores para generar un ejemplo y disciplina en el equipo.','Tener una conversación privada con los miembros incumplidores, estableciendo expectativas claras y consecuencias por no cumplir, es la acción más adecuada como líder. Ignorar el incumplimiento o reasignar tareas solo perpetúa el problema y puede generar resentimiento en otros miembros. Sancionar públicamente también puede afectar negativamente el ambiente de trabajo. Al tener una conversación privada, se establecen expectativas claras y se brinda la oportunidad de corregir el comportamiento y comprometerse con el cumplimiento de las responsabilidades asignadas.'),
    (6,'Estás liderando un equipo en el que hay diferentes niveles de habilidades y conocimientos. ¿Cuál sería la estrategia más efectiva para aprovechar el potencial del equipo?','Fomentar la colaboración y el intercambio de conocimientos entre los miembros del equipo.','Asignar tareas de acuerdo a las habilidades individuales, evitando desafiar a los miembros más competentes.','Ignorar las diferencias de habilidades y conocimientos, dejando que cada miembro se desarrolle de forma independiente.','Limitar las tareas y responsabilidades a los miembros con mayor experiencia y conocimientos.','Permite involucrar al equipo en la toma de decisiones y fomenta la participación y la diversidad de ideas. Al realizar una lluvia de ideas en equipo, se pueden identificar y seleccionar las ideas más relevantes y viables, maximizando el potencial creativo del equipo y generando un mayor sentido de propiedad y compromiso hacia las soluciones seleccionadas. '),
    (7,'Te encuentras liderando un equipo en el que surgen constantemente ideas innovadoras por parte de los miembros. Sin embargo, debido a restricciones de tiempo, no es posible implementar todas las ideas. ¿Cuál sería la decisión más acertada como líder? ','Realizar una lluvia de ideas en equipo para priorizar las ideas más relevantes. ','Ignorar todas las ideas y continuar con la planificación inicial.','Seleccionar únicamente las ideas que te parezcan más prometedoras.','Delegar la responsabilidad de selección de ideas a otro miembro del equipo.','Porque implica abordar la situación de manera constructiva y apoyar al miembro del equipo en la corrección del error. Brindar retroalimentación constructiva permite comunicar de forma clara y respetuosa la situación y proporcionar orientación para corregir el rumbo. Además, ofrecer apoyo demuestra el interés por el desarrollo y el crecimiento del miembro del equipo, fomentando un ambiente de aprendizaje y mejora continua.'),
    (8,'Como líder de un proyecto, te das cuenta de que un miembro del equipo está trabajando en una tarea incorrecta y desperdiciando reModulos. Sin embargo, este miembro tiene una actitud defensiva cuando se le confronta. ¿Cómo abordarías esta situación?','Brindar retroalimentación constructiva y ofrecer apoyo para corregir el error.','Ignorar la situación y permitir que el miembro continúe con su tarea.','Despedir al miembro del equipo por su falta de rendimiento.','Reasignar al miembro a una tarea diferente sin dar explicaciones.','Implica abordar el problema de manera proactiva y brindar apoyo individualizado a los miembros con dificultades. Al realizar reuniones individuales, se pueden identificar las causas subyacentes de las dificultades, como falta de reModulos, falta de habilidades o sobrecarga de trabajo, y proporcionar apoyo adecuado para superar los desafíos. Esta acción promueve la confianza y la mejora del rendimiento individual y del equipo en general.'),
    (9,'Estás liderando un equipo en el que algunos miembros tienen dificultades para cumplir con los plazos establecidos. Como líder, ¿cuál sería la mejor acción a tomar?','Realizar una reunión individual con cada miembro para identificar las causas de las dificultades y brindar apoyo.','Ignorar las dificultades de los miembros y culparlos por no cumplir con los plazos.','Establecer plazos más cortos y exigir un mayor esfuerzo a los miembros.','Reasignar las tareas de los miembros que tienen dificultades a otros miembros más eficientes. ','implica abordar el problema de manera proactiva y brindar apoyo individualizado a los miembros con dificultades. Al realizar reuniones individuales, se pueden identificar las causas subyacentes de las dificultades, como falta de reModulos, falta de habilidades o sobrecarga de trabajo, y proporcionar apoyo adecuado para superar los desafíos. Esta acción promueve la confianza y la mejora del rendimiento individual y del equipo en general. '),
    (10,'En una reunión de equipo, surgen diferentes opiniones respecto a la mejor estrategia a seguir para abordar un desafío importante. Como líder, ¿cuál sería tu enfoque para tomar una decisión?','Facilitar una discusión abierta y tomar una decisión basada en consenso.','Ignorar las opiniones y tomar una decisión unilateralmente.','Tomar en cuenta únicamente las opiniones de los miembros con más experiencia.','Delegar la responsabilidad de la toma de decisión a otro miembro del equipo.','promueve la participación y la diversidad de ideas en la toma de decisiones. Facilitar una discusión abierta permite que los diferentes puntos de vista sean expresados y debatidos, lo que enriquece la toma de decisiones. Tomar una decisión basada en consenso implica encontrar un punto medio o una solución que sea aceptable para la mayoría de los miembros, fomentando el compromiso y la responsabilidad compartida hacia la decisión tomada. '),
    (11,'Estás liderando un equipo multicultural en el que se han presentado malentendidos y conflictos debido a diferencias culturales. ¿Cuál sería la mejor estrategia como líder para abordar esta situación?','Facilitar el diálogo abierto y el entendimiento mutuo entre los miembros del equipo. ','Ignorar las diferencias culturales y tratar de imponer una cultura única en el equipo.','Establecer reglas estrictas para evitar la expresión de diferencias culturales.','Reasignar a los miembros del equipo a grupos separados basados en su cultura.','promueve el respeto, la comunicación y el entendimiento mutuo entre los miembros del equipo multicultural. Al facilitar el diálogo abierto, se pueden abordar los malentendidos y los conflictos surgidos por las diferencias culturales, permitiendo a los miembros compartir sus perspectivas y encontrar puntos de conexión. Esta estrategia fomenta un ambiente inclusivo y fortalece la cohesión del equipo.'),
    (12,'Como líder de un equipo, te enfrentas a un proyecto importante con un plazo ajustado. Uno de tus miembros está experimentando dificultades personales que afectan su rendimiento. ¿Cuál es la mejor opción de liderazgo en esta situación?','Brindarle apoyo emocional y flexibilidad en sus responsabilidades.','Asignarle tareas más sencillas para aliviar su carga.','Ignorar su situación personal y exigirle que cumpla con el plazo establecido.','Reemplazarlo por otro miembro más capacitado.','En esta situación, la opción correcta es brindar apoyo emocional y flexibilidad al miembro del equipo que enfrenta dificultades personales. Como líder, es importante mostrar empatía y comprensión, ofreciendo apoyo emocional y ajustando las responsabilidades para adaptarse a su situación. Esto no solo demuestra preocupación por el bienestar del miembro del equipo, sino que también puede ayudarlo a recuperar su rendimiento y contribuir al éxito del proyecto.'),
    (13,'Tu equipo está debatiendo sobre la mejor manera de abordar un problema complejo. Dos miembros tienen opiniones opuestas y el debate se está volviendo acalorado. ¿Cuál es la mejor estrategia de liderazgo en esta situación? ','Facilitar una discusión respetuosa y guiar al equipo hacia un consenso.','Tomar partido por uno de los miembros y cerrar el debate.','Evitar el debate y tomar la decisión por tu cuenta.','Permitir que el debate continúe indefinidamente hasta que lleguen a un acuerdo.','En situaciones de debate acalorado, la mejor estrategia de liderazgo es facilitar una discusión respetuosa y guiar al equipo hacia un consenso. Como líder, debes actuar como mediador y fomentar un ambiente de respeto, escuchando las opiniones de ambos lados y buscando puntos en común. Guiar al equipo hacia un consenso ayuda a encontrar una solución que sea aceptable para todos y promueve la colaboración y el compromiso del equipo. '),
    (14,'Durante una reunión de equipo, un miembro se muestra reacio a compartir sus ideas y opiniones. ¿Cuál es la mejor manera de fomentar su participación como líder?','Brindarle un entorno seguro y alentar su participación de manera gradual.','Ignorar su falta de participación y continuar con la reunión.','Exigirle que comparta sus ideas y opiniones de inmediato.','Reemplazarlo por otro miembro más participativo.','Para fomentar la participación de un miembro reacio, la mejor opción es brindarle un entorno seguro y alentar su participación de manera gradual. Como líder, debes crear un ambiente en el que todos los miembros se sientan cómodos compartiendo sus ideas y opiniones. Puedes comenzar alentando su participación en momentos menos intimidantes y proporcionando retroalimentación positiva cuando comparta. Esto ayudará a construir confianza y eventualmente fomentará una mayor participación del miembro en cuestión. '),
    (15,'En tu equipo, hay un miembro que suele tomar la iniciativa y asumir la mayoría de las responsabilidades. Sin embargo, esto ha llevado a una falta de equilibrio en la distribución del trabajo. ¿Cuál es la mejor estrategia de liderazgo para abordar esta situación?','Reasignar tareas para equilibrar la carga de trabajo de manera más justa.','Reconocer el esfuerzo del miembro y permitirle continuar asumiendo la mayoría de las responsabilidades.','Ignorar la falta de equilibrio y esperar a que se solucione por sí sola.','Reemplazar al miembro por otro que pueda asumir más responsabilidades. ','Para abordar la falta de equilibrio en la distribución del trabajo, la mejor estrategia de liderazgo es reasignar tareas para equilibrar la carga de trabajo de manera más justa. Como líder, es importante reconocer el esfuerzo del miembro proactivo, pero también es esencial fomentar una cultura de trabajo en equipo y colaboración equitativa. Reasignar tareas ayudará a evitar el agotamiento y promoverá una mayor participación y compromiso de todos los miembros del equipo.'),
    (16,'Un miembro del equipo ha cometido un error importante que ha afectado negativamente un proyecto. ¿Cuál es la mejor manera de abordar la situación como líder?','Brindar retroalimentación constructiva y ayudar al miembro a aprender de la experiencia.','Castigar al miembro del equipo para establecer un ejemplo para los demás.','Ignorar el error y continuar con el proyecto.','Reemplazar al miembro por otro que no cometa errores.','Cuando un miembro comete un error importante, la mejor manera de abordarlo como líder es brindar retroalimentación constructiva y ayudar al miembro a aprender de la experiencia. Es importante mantener una actitud de apoyo y enfoque en el aprendizaje y la mejora, en lugar de castigar o ignorar el error. Al proporcionar retroalimentación constructiva, puedes ayudar al miembro a comprender las lecciones aprendidas y evitar la repetición de errores en el futuro.'),
    (17,'Te encuentras liderando un equipo en el que hay discrepancias entre los miembros sobre la dirección a seguir en un proyecto importante. ¿Cuál de las siguientes acciones sería la más apropiada para abordar esta situación?','Facilitar una reunión de discusión en la que todos los miembros puedan expresar sus puntos de vista y llegar a un consenso.','Tomar la decisión unilateralmente y comunicarla al equipo sin tener en cuenta sus opiniones.','Realizar una votación entre los miembros del equipo y seguir la opción con mayor votos.','Delegar la toma de decisiones en uno de los miembros del equipo para evitar conflictos.','Esta opción es la más apropiada ya que promueve la participación y la colaboración del equipo en la toma de decisiones. Al facilitar una reunión de discusión, se brinda un espacio para que todos los miembros expresen sus opiniones, compartan sus ideas y trabajen juntos para llegar a un consenso sobre la dirección a seguir en el proyecto. Esto fomenta el compromiso y la responsabilidad colectiva, fortaleciendo el equipo y aumentando las posibilidades de éxito.'),
    (18,'En tu equipo, uno de los miembros ha cometido un error grave que ha afectado negativamente a un proyecto. ¿Cuál de las siguientes acciones sería la más apropiada como líder?','Conversar de manera privada con el miembro para entender lo sucedido y buscar soluciones.','Reaccionar con enojo y castigar al miembro del equipo públicamente.','Ignorar el error y esperar a que se solucione por sí mismo.','Culpar al miembro del equipo sin indagar en los detalles del error.','Esta opción es la más apropiada porque promueve la comunicación abierta y el entendimiento mutuo. Al conversar de manera privada con el miembro del equipo, se brinda la oportunidad de entender las circunstancias que llevaron al error, identificar lecciones aprendidas y trabajar en conjunto para buscar soluciones y evitar que el error se repita en el futuro. Además, esta acción muestra respeto hacia el miembro y fomenta un ambiente de aprendizaje y crecimiento.'),
    (19,'Tu equipo se encuentra enfrentando un proyecto complejo y con plazos ajustados. Sin embargo, uno de los miembros está experimentando dificultades y no está logrando cumplir con sus responsabilidades. ¿Cuál de las siguientes acciones sería la más adecuada como líder? ','Conversar de manera privada con el miembro para entender las dificultades y ofrecer apoyo.','Ignorar la situación y asignar las tareas del miembro a otros colaboradores.','Reasignar al miembro a tareas menos desafiantes para evitar problemas adicionales.','Culpar al miembro y tomar acciones disciplinarias de inmediato. ','Esta opción es la más adecuada porque fomenta el apoyo y la resolución colaborativa de problemas. Al conversar de manera privada con el miembro, se brinda la oportunidad de entender las dificultades que está enfrentando y ofrecer apoyo adicional para superar los desafíos. Esto permite abordar la situación de manera empática y constructiva, promoviendo el crecimiento individual y fortaleciendo la cohesión del equipo.'),
    (20,'Tu equipo ha presentado una idea innovadora para mejorar los procesos internos de la organización. Sin embargo, algunos miembros de la alta dirección se muestran escépticos y no muestran interés en implementarla. ¿Cuál de las siguientes acciones sería la más apropiada como líder?','Conversar con los miembros escépticos para entender sus preocupaciones y buscar una solución conjunta.','Desestimar la idea y seguir con los procesos existentes para evitar conflictos con la alta dirección.','Ignorar la opinión de la alta dirección y llevar adelante la implementación de la idea.','Comunicar la idea directamente a la alta dirección sin involucrar al equipo en el proceso.','Esta opción es la más apropiada porque promueve la comunicación y la búsqueda de consenso. Al conversar con los miembros escépticos, se brinda la oportunidad de entender sus preocupaciones y perspectivas. Esto permite abordar sus objeciones de manera constructiva, buscar puntos en común y trabajar juntos para encontrar una solución que pueda satisfacer tanto a los miembros escépticos como a la alta dirección. Esta acción demuestra habilidades de negociación y facilita el proceso de implementación de la idea innovadora. '),
    (21,'En tu equipo, uno de los miembros ha demostrado un desempeño excepcional y ha logrado resultados destacados en un proyecto. ¿Cuál de las siguientes acciones sería la más adecuada como líder?','Reconocer al miembro públicamente y compartir los resultados con el resto del equipo.','Ignorar los logros del miembro y no reconocer su desempeño. ','Reconocer y felicitar al miembro en privado por sus logros.','Mantener el reconocimiento en privado y no involucrar al resto del equipo.','Esta opción es la más adecuada porque promueve la motivación y el reconocimiento en el equipo. Al reconocer al miembro públicamente y compartir los resultados destacados, se demuestra la valoración del desempeño excepcional y se motiva al resto del equipo a seguir su ejemplo. Además, el reconocimiento público fomenta un ambiente de trabajo positivo y fortalece la confianza y la colaboración en el equipo.'),
    (22,'Como líder de un equipo, te enfrentas a una situación en la que dos miembros del equipo tienen una fuerte diferencia de opiniones sobre la dirección a seguir en un proyecto importante. ¿Cuál sería la estrategia más efectiva para abordar esta situación?','Fomentar el debate constructivo y la búsqueda de un consenso entre los miembros.','Tomar una decisión unilateral y comunicarla al equipo. ','Ignorar la situación y esperar a que los miembros resuelvan el conflicto por sí mismos.','Apartar a uno de los miembros del proyecto para evitar confrontaciones.','Esta opción es la más efectiva porque promueve la participación activa de los miembros del equipo y la colaboración en la toma de decisiones. Fomentar el debate constructivo permite que se expresen diferentes perspectivas y se consideren múltiples ideas, lo que puede llevar a encontrar un consenso y a tomar una decisión que sea respaldada por todos los involucrados. '),
    (23,'En un equipo, un miembro muestra un bajo rendimiento y no cumple con las expectativas del proyecto. ¿Cuál de las siguientes acciones sería más apropiada como líder?','Ofrecer apoyo y orientación al miembro para mejorar su rendimiento. ','Ignorar el bajo rendimiento y esperar a que mejore por sí solo.','Tomar medidas disciplinarias inmediatas y aplicar sanciones.','Apartar al miembro del equipo sin ofrecerle una oportunidad de mejora.','Esta opción es la más adecuada porque como líder, es importante brindar apoyo y orientación a los miembros del equipo que están enfrentando dificultades. Al ofrecerles la oportunidad de mejorar su rendimiento y proporcionarles reModulos y apoyo necesarios, se fomenta el crecimiento y se promueve una cultura de desarrollo en el equipo.'),
    (24,'En un equipo, un miembro muestra un bajo rendimiento y no cumple con las expectativas del proyecto. ¿Cuál de las siguientes acciones sería más apropiada como líder?','Ofrecer apoyo y orientación al miembro para mejorar su rendimiento. ','Ignorar el bajo rendimiento y esperar a que mejore por sí solo.','Tomar medidas disciplinarias inmediatas y aplicar sanciones.','Apartar al miembro del equipo sin ofrecerle una oportunidad de mejora.','Esta opción es la más adecuada porque como líder, es importante brindar apoyo y orientación a los miembros del equipo que están enfrentando dificultades. Al ofrecerles la oportunidad de mejorar su rendimiento y proporcionarles reModulos y apoyo necesarios, se fomenta el crecimiento y se promueve una cultura de desarrollo en el equipo.'),
    (25,'Te enfrentas a una situación en la que dos miembros de tu equipo tienen diferentes estilos de trabajo y enfoques para abordar un proyecto. ¿Cuál de las siguientes estrategias de liderazgo sería la más apropiada?','Facilitar una reunión de equipo para discutir y encontrar un enfoque que combine las fortalezas de ambos miembros.','Forzar a ambos miembros a adoptar el mismo estilo de trabajo. ','Delegar tareas específicas a cada miembro de acuerdo con sus fortalezas.','Ignorar las diferencias y permitir que los miembros resuelvan el conflicto por sí mismos.','Esta opción es la más adecuada porque promueve la colaboración y la sinergia entre los miembros del equipo. Facilitar una reunión de equipo les brinda la oportunidad de discutir y compartir sus enfoques, y juntos encontrar un enfoque que combine las fortalezas individuales de ambos miembros. Esto permite aprovechar las habilidades complementarias y promover un ambiente de trabajo armonioso.'),
    (26,'En tu equipo, un miembro ha cometido un error que ha tenido un impacto negativo en el proyecto. ¿Cuál de las siguientes acciones sería la más apropiada como líder?','Ofrecer apoyo al miembro y trabajar juntos para encontrar una solución al error.','Culpar y criticar públicamente al miembro por el error cometido.','Apartar al miembro del proyecto y asignar la tarea a otro miembro.','Ignorar el error y esperar a que el miembro lo resuelva por sí solo.','Esta opción es la más efectiva porque como líder, es importante brindar apoyo a los miembros del equipo cuando cometen errores. Ofrecer apoyo y trabajar juntos para encontrar una solución no solo ayuda a corregir el error, sino que también fortalece la confianza y el compromiso en el equipo. El aprendizaje de los errores y la mejora conjunta son fundamentales para el crecimiento y el desarrollo del equipo.'),
    (27,'Un miembro de tu equipo está experimentando dificultades personales que afectan su rendimiento en el trabajo. ¿Cuál sería la mejor estrategia de liderazgo para abordar esta situación?','Ofrecer apoyo emocional y flexibilidad en la carga de trabajo para el miembro. ','Ignorar las dificultades personales y enfocarse únicamente en el rendimiento laboral.','Reasignar las tareas del miembro a otros miembros del equipo. ','Tomar medidas disciplinarias inmediatas y aplicar sanciones.','Esta opción es la más adecuada porque muestra empatía y comprensión hacia las dificultades personales del miembro. Ofrecer apoyo emocional y flexibilidad en la carga de trabajo demuestra que te preocupas por el bienestar de tus miembros y estás dispuesto a apoyarlos durante momentos difíciles. Esto puede ayudar al miembro a superar sus dificultades y a mantener su rendimiento en el trabajo.'),
    (28,'Un miembro de tu equipo está experimentando dificultades personales que afectan su rendimiento en el trabajo. ¿Cuál sería la mejor estrategia de liderazgo para abordar esta situación?','Ofrecer apoyo emocional y flexibilidad en la carga de trabajo para el miembro. ','Ignorar las dificultades personales y enfocarse únicamente en el rendimiento laboral.','Reasignar las tareas del miembro a otros miembros del equipo. ','Tomar medidas disciplinarias inmediatas y aplicar sanciones.','Esta opción es la más adecuada porque muestra empatía y comprensión hacia las dificultades personales del miembro. Ofrecer apoyo emocional y flexibilidad en la carga de trabajo demuestra que te preocupas por el bienestar de tus miembros y estás dispuesto a apoyarlos durante momentos difíciles. Esto puede ayudar al miembro a superar sus dificultades y a mantener su rendimiento en el trabajo.'),
    (29,'Tu equipo se encuentra trabajando en un proyecto con un plazo de entrega ajustado y alta presión. Uno de los miembros está luchando por cumplir con las fechas límite. ¿Cuál sería la mejor estrategia de liderazgo para abordar esta situación?','Ofrecer apoyo al miembro y buscar soluciones para ayudarlo a cumplir con las fechas límite.','Exigir al miembro que cumpla con las fechas límite y aplicar medidas disciplinarias en caso de incumplimiento.','Asignar tareas adicionales al miembro para compensar su falta de rendimiento. ','Apartar al miembro del proyecto y asignar las tareas a otros miembros. ','Esta opción es la más efectiva porque muestra comprensión y apoyo hacia el miembro que está luchando por cumplir con las fechas límite. Como líder, es importante ofrecer apoyo y buscar soluciones conjuntas para ayudar al miembro a cumplir con sus responsabilidades. Esto fortalece la confianza y la colaboración en el equipo, y aumenta las posibilidades de éxito en el proyecto.'),
    (30,'Como líder de un equipo, te enfrentas a una decisión importante que afectará a los miembros de tu equipo. Algunos miembros están a favor de una opción, mientras que otros apoyan una alternativa diferente. ¿Cuál sería la estrategia más efectiva para tomar esta decisión?','Facilitar una discusión abierta y constructiva para analizar las diferentes perspectivas y tomar una decisión fundamentada.','Ignorar las opiniones de los miembros y tomar la decisión basándote en tu propia perspectiva.','Delegar la decisión a los miembros del equipo y dejar que lleguen a un consenso.','Realizar una votación para determinar la opción preferida por la mayoría.','Facilitar una discusión abierta y constructiva permite que los miembros del equipo expresen sus puntos de vista, compartan ideas y argumenten a favor de sus alternativas. Esto promueve la participación y la colaboración, y brinda la oportunidad de tomar una decisión fundamentada, considerando diferentes perspectivas y maximizando el compromiso y el apoyo del equipo. '),
    (31,'Tu equipo se encuentra ante un desafío complejo y urgente. Tienes la opción de tomar el liderazgo total y dirigir las acciones del equipo, o darles libertad para que se organicen y aborden el desafío de manera autónoma. ¿Cuál sería la estrategia más efectiva en esta situación?','Establecer un enfoque mixto, proporcionando dirección general y permitiendo que el equipo tome decisiones específicas.','Tomar el liderazgo total y dirigir las acciones del equipo para garantizar una respuesta rápida y coordinada.','Dar libertad al equipo para que se organicen y aborden el desafío de manera autónoma, confiando en sus capacidades.','Reunir al equipo y solicitar su opinión sobre qué estrategia prefieren seguir. ','En esta situación, establecer un enfoque mixto es lo más efectivo. Proporcionar dirección general permite que el equipo sepa hacia dónde dirigirse y cuál es el objetivo final, mientras que permitir que el equipo tome decisiones específicas fomenta la autonomía y la responsabilidad individual. Esto promueve la creatividad, el compromiso y la capacidad de respuesta del equipo ante el desafío complejo y urgente.'),
    (32,'Te enfrentas a un conflicto entre dos miembros de tu equipo que está afectando la colaboración y la comunicación. ¿Cuál sería la estrategia más adecuada para resolver este conflicto?','Facilitar una reunión mediada en la que ambos miembros puedan expresar sus puntos de vista y encontrar una solución conjunta.','Ignorar el conflicto y esperar a que se resuelva por sí solo.','Tomar partido por uno de los miembros y establecer una decisión unilateral.','Decidir apartar a uno de los miembros del equipo para evitar futuros conflictos.','Facilitar una reunión mediada es la estrategia más adecuada para resolver el conflicto. Proporcionar un espacio seguro para que ambos miembros expresen sus puntos de vista y escucharse mutuamente promueve la comunicación abierta y el entendimiento. A través de esta mediación, se busca encontrar una solución conjunta que aborde las preocupaciones y necesidades de ambas partes, fomentando la colaboración y la resolución pacífica del conflicto.'),
    (33,'Tu equipo ha estado trabajando arduamente en un proyecto, pero enfrentan dificultades y no logran los resultados esperados. ¿Cuál sería la mejor manera de motivar al equipo y aumentar su compromiso?','Proporcionar retroalimentación constructiva y reconocer los esfuerzos y logros del equipo en su conjunto.','Establecer sanciones para los miembros del equipo que no cumplan con las expectativas.','Dar recompensas individuales a los miembros más destacados para incentivar su rendimiento.','Incrementar la carga de trabajo para impulsar la productividad del equipo.','Proporcionar retroalimentación constructiva y reconocer los esfuerzos y logros del equipo en su conjunto es la mejor manera de motivar al equipo y aumentar su compromiso. La retroalimentación constructiva ayuda a identificar áreas de mejora y brinda orientación para superar las dificultades, mientras que el reconocimiento colectivo refuerza el sentido de pertenencia y el trabajo en equipo. Esto promueve la motivación intrínseca y el compromiso del equipo hacia el logro de los objetivos del proyecto.'),
    (34,'Estás liderando un equipo multicultural en el que las diferencias culturales han generado malentendidos y conflictos. ¿Cuál sería una estrategia eficaz para fomentar la comprensión y la colaboración entre los miembros del equipo?','Facilitar sesiones de capacitación y actividades que promuevan el entendimiento cultural y la apreciación de las diferencias.','Ignorar las diferencias culturales y enfocarse únicamente en las tareas del equipo.','Establecer reglas estrictas para minimizar las interacciones personales y evitar conflictos.','Separar a los miembros del equipo según sus culturas y asignarles tareas individuales.','Facilitar sesiones de capacitación y actividades que promuevan el entendimiento cultural y la apreciación de las diferencias es una estrategia efectiva. Esto ayuda a los miembros del equipo a comprender y valorar las diversas perspectivas culturales, promoviendo la empatía y la colaboración. Al entender mejor las diferencias culturales, se pueden evitar malentendidos y conflictos, y se fomenta un ambiente de trabajo inclusivo y productivo.'),
    (35,'Estás liderando un equipo multicultural en el que las diferencias culturales han generado malentendidos y conflictos. ¿Cuál sería una estrategia eficaz para fomentar la comprensión y la colaboración entre los miembros del equipo?','Facilitar sesiones de capacitación y actividades que promuevan el entendimiento cultural y la apreciación de las diferencias.','Ignorar las diferencias culturales y enfocarse únicamente en las tareas del equipo.','Establecer reglas estrictas para minimizar las interacciones personales y evitar conflictos.','Separar a los miembros del equipo según sus culturas y asignarles tareas individuales.','Facilitar sesiones de capacitación y actividades que promuevan el entendimiento cultural y la apreciación de las diferencias es una estrategia efectiva. Esto ayuda a los miembros del equipo a comprender y valorar las diversas perspectivas culturales, promoviendo la empatía y la colaboración. Al entender mejor las diferencias culturales, se pueden evitar malentendidos y conflictos, y se fomenta un ambiente de trabajo inclusivo y productivo.'),
    (36,'Te encuentras liderando un equipo en el que dos miembros clave están en desacuerdo sobre cómo abordar un proyecto importante. Ambos tienen argumentos sólidos y puntos de vista diferentes. ¿Cuál sería la mejor opción de liderazgo para manejar esta situación?','Liderazgo participativo, facilitando una discusión abierta para que los miembros del equipo lleguen a un consenso.','Liderazgo autocrático, imponiendo tu propia solución y desestimando las opiniones de los miembros del equipo.','Liderazgo burocrático, siguiendo un proceso estructurado y tomando una decisión basada en reglas predefinidas.','Liderazgo transaccional, ofreciendo incentivos individuales para obtener la conformidad de los miembros del equipo.','El liderazgo participativo es la mejor opción para abordar un desacuerdo entre dos miembros clave. Al facilitar una discusión abierta y permitir que ambos miembros expresen sus puntos de vista, se fomenta el diálogo constructivo y se busca un consenso. Esta estrategia promueve la colaboración y aumenta las posibilidades de encontrar una solución aceptada por ambas partes.'),
    (37,'Estás liderando un equipo en el que algunos miembros no están cumpliendo con sus responsabilidades y esto está afectando el rendimiento general. ¿Cuál sería la mejor estrategia de liderazgo para abordar esta situación?','Liderazgo transformacional, brindando apoyo y orientación a los miembros para ayudarles a cumplir con sus responsabilidades.','Liderazgo autocrático, tomando medidas disciplinarias inmediatas para garantizar el cumplimiento de las responsabilidades.','Liderazgo burocrático, estableciendo reglas estrictas y procedimientos disciplinarios para mantener el orden en el equipo.','Liderazgo transaccional, ofreciendo incentivos individuales para motivar a los miembros a cumplir con sus responsabilidades.','El liderazgo transformacional es la mejor opción para abordar miembros del equipo que no cumplen con sus responsabilidades. En lugar de tomar medidas disciplinarias inmediatas, el líder transformacional brinda apoyo y orientación a los miembros, identifica las barreras que están impidiendo el cumplimiento de las responsabilidades y ofrece soluciones para superarlas. Esto promueve el crecimiento individual y fomenta un entorno de apoyo en el equipo.'),
    (38,'Te encuentras liderando un equipo en el que hay diferentes perspectivas sobre una decisión importante que afectará a toda la organización. ¿Cuál sería la mejor estrategia de liderazgo para tomar una decisión efectiva en este contexto?','Liderazgo participativo, involucrando a los miembros en la toma de decisiones a través de debates y discusiones.','Liderazgo autocrático, tomando la decisión sin consultar a los miembros del equipo.','Liderazgo burocrático, siguiendo un proceso establecido para la toma de decisiones.','Liderazgo transaccional, ofreciendo incentivos a los miembros del equipo para obtener su conformidad.','El liderazgo participativo es la mejor estrategia para tomar una decisión efectiva cuando hay diferentes perspectivas en juego. Al involucrar a los miembros del equipo en debates y discusiones, se obtienen diferentes puntos de vista y se pueden considerar múltiples opciones antes de tomar una decisión final. Esto aumenta la calidad de la decisión y promueve el compromiso del equipo con la implementación.'),
    (39,'Estás liderando un equipo que se enfrenta a un plazo ajustado para entregar un proyecto. Sin embargo, algunos miembros están sobrecargados de trabajo, mientras que otros tienen capacidad para ayudar. ¿Cuál sería la mejor estrategia de liderazgo para abordar esta situación?','Liderazgo transformacional, fomentando la colaboración y el apoyo entre los miembros del equipo.','Liderazgo autocrático, asignando tareas adicionales a los miembros que tienen menos carga de trabajo. ','Liderazgo burocrático, siguiendo un procedimiento estándar para distribuir equitativamente las tareas.','Liderazgo transaccional, ofreciendo incentivos individuales para que los miembros asuman tareas adicionales.','El liderazgo transformacional es la mejor opción para abordar una situación en la que algunos miembros están sobrecargados de trabajo y otros tienen capacidad para ayudar. Fomentar la colaboración y el apoyo entre los miembros del equipo permite que se compartan tareas de manera equitativa, se aprovechen las fortalezas individuales y se alcance el objetivo de entregar el proyecto dentro del plazo establecido.'),
    (40,'Estás liderando un equipo en el que algunos miembros están desmotivados y han perdido interés en el trabajo. ¿Cuál sería la mejor estrategia de liderazgo para abordar esta situación?','Liderazgo transformacional, inspirando y motivando a los miembros a través de una visión inspiradora y metas desafiantes.','Liderazgo autocrático, imponiendo expectativas y disciplina para recuperar la motivación de los miembros.','Liderazgo burocrático, estableciendo reglas y procedimientos rígidos para aumentar la motivación de los miembros.','Liderazgo transaccional, ofreciendo incentivos individuales para recuperar la motivación de los miembros.','El liderazgo transformacional es la mejor estrategia para abordar la falta de motivación y el desinterés en el trabajo. Al inspirar y motivar a los miembros a través de una visión inspiradora y metas desafiantes, el líder transformacional estimula el compromiso y la pasión en el equipo. Esto fomenta un ambiente de trabajo motivador y ayuda a los miembros a recuperar su interés y dedicación al trabajo.');
